from .generation_pipeline import SamplesData

class SamplesLib:
    def __init__(self):
        '''
        Autogenerated Samples Library
        '''
        self.sgp = SamplesData()

        self.hh = {
                'bars': self.sgp.bars,
                'bars_len': self.sgp.bars_len,
                'time_signature': self.sgp.time_signature,
                'notes': self.sgp.chosen_notes,
                'notes_len': self.sgp.notes_len,
                'time_left': self.sgp.time_left,
                'swing': self.sgp.swing,
                'samples': [],
                'bars_time': []
            }

    